import "@/app/globals.css"
import { Inter } from 'next/font/google'
import { ThemeProvider } from "@/providers/ThemeProvider"
import Navbar from "@/components/Navbar"
import SiteFooter from "@/components/SiteFooter"
import { TailwindIndicator } from "@/components/TailwindIndicator"
import { Metadata } from "next"
import TanstackProvider from "@/providers/TanstackProvider"


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}




interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
              <div className="container relative flex min-h-screen flex-col">
                <Navbar />
                <main className="flex-1">
                  <TanstackProvider>
                    {children}
                  </TanstackProvider>
                </main>
                <SiteFooter />
              </div>
              <TailwindIndicator />
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}
